{% set name = "surya-ocr" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/surya_ocr-{{ version }}.tar.gz
  sha256: eae8ce47e1873d42a0e35d58205dc7378dc813021b68881854e446d3e4a3a95e

build:
  entry_points:
    - surya_detect = detect_text:main
    - surya_ocr = ocr_text:main
    - surya_layout = detect_layout:main
    - surya_gui = run_ocr_app:run_app
    - surya_order = reading_order:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13,!=3.9.7
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.13,!=3.9.7
    - transformers >=4.41.0,<5.0.0
    - pytorch >=2.4.1,<3.0.0
    - pydantic >=2.5.3,<3.0.0
    - pydantic-settings >=2.1.0,<3.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - pillow >=10.2.0,<11.0.0
    - pypdfium2 >=4.25.0,<5.0.0
    - opencv >=4.9.0,<5.0.0
    - tabulate >=0.9.0,<0.10.0
    - filetype >=1.2.0,<2.0.0
    - ftfy >=6.1.3,<7.0.0
    - streamlit
    - pdftext >=0.4.0,<0.5.0

test:
  imports:
    - surya
  commands:
    - pip check
    - surya_detect --help
    - surya_ocr --help
    - surya_layout --help
    - surya_order --help
  requires:
    - pip

about:
  home: https://github.com/VikParuchuri/surya
  summary: OCR, layout, reading order, and line detection in 90+ languages
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
